version: "3.3"

networks:
  proxy:
    external: 
      name: proxy
  internal:
    internal: true

services:

  wallabag-db:
    image: mariadb
    container_name: wallabag-db
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_PASSWORD=mysql
      - MYSQL_DATABASE=wallabag
      - MYSQL_USER=wallabag
    volumes:
      - /opt/wallabag/data:/var/lib/mysql
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=false"
    networks:
      - internal
    restart: unless-stopped

  wallabag-redis:
    image: redis:alpine
    container_name: wallabag-redis
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=false"
    networks:
      - internal
    restart: unless-stopped

  wallabag-app:
    image: wallabag/wallabag:latest
    container_name: wallabag-app
    depends_on:
      - wallabag-db
      - wallabag-redis
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - SYMFONY__ENV__DATABASE_DRIVER=pdo_mysql
      - SYMFONY__ENV__DATABASE_HOST=wallabag-db
      - SYMFONY__ENV__DATABASE_PORT=3306
      - SYMFONY__ENV__DATABASE_NAME=wallabag
      - SYMFONY__ENV__DATABASE_USER=wallabag
      - SYMFONY__ENV__DATABASE_PASSWORD=mysql
      - SYMFONY__ENV__DATABASE_CHARSET=utf8mb4
      - SYMFONY__ENV__MAILER_HOST=127.0.0.1
      - SYMFONY__ENV__MAILER_USER=~
      - SYMFONY__ENV__MAILER_PASSWORD=~
      - SYMFONY__ENV__FROM_EMAIL=${LETSENCRYPT_EMAIL}
      - SYMFONY__ENV__DOMAIN_NAME=https://${SUBDOMAIN}.${DOMAIN}
      - SYMFONY__ENV__REDIS_HOST=wallabag-redis
    volumes:
      - /opt/wallabag/images:/var/www/wallabag/web/assets/images
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wallabag-app.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.wallabag-app.entrypoints=websecure"
      - "traefik.http.routers.wallabag-app.tls.certresolver=myresolver"
    networks:
      - proxy
      - internal
    restart: unless-stopped