version: "2.1"

networks:
  proxy:
    external:
      name: proxy

volumes:
  sonarr-config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${STORAGE_ROOT}/docker/sonarr/config
  sonarr-series-dir:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${STORAGE_ROOT}/video/Series
  sonarr-downloads-dir:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${STORAGE_ROOT}/downloads
  # Example When mounting remote NFS dir:
  # sonarr-downloads-dir:
  #   driver: local
  #   driver_opts:
  #     type: nfs4
  #     o: "addr=${NFS_REMOTE_IP},rw"
  #     device: ":${NFS_REMOTE_PATH}"

services:
  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - UMASK_SET=022 #optional
    volumes:
      - sonarr-config:/config
      - sonarr-series-dir:/tv
      - sonarr-downloads-dir:/downloads
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.entrypoints=http"
      - "traefik.http.routers.sonarr.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.sonarr.middlewares=https-only@file"
      - "traefik.http.routers.sonarr-secure.entrypoints=https"
      - "traefik.http.routers.sonarr-secure.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.sonarr-secure.tls=true"
      - "traefik.http.routers.sonarr-secure.tls.certresolver=le-dns"
      - "traefik.http.routers.sonarr-secure.service=sonarr"
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
    networks:
      - proxy
    restart: unless-stopped