version: '3.7'

networks:
  proxy:
    external: 
      name: proxy
  internal:
    internal: true

volumes:
  public:
  storage:
  invoiceninja-public:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${STORAGE_ROOT}/docker/invoiceninja/public

  invoiceninja-storage:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${STORAGE_ROOT}/docker/invoiceninja/storage

  invoiceninja-database:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${STORAGE_ROOT}/docker/invoiceninja/database

services:
  invoiceninja-db:
    container_name: invoiceninja-db
    image: mariadb:latest
    security_opt:
      - no-new-privileges:true
    networks:
      - internal
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
      - MYSQL_DATABASE=ninja
      - MYSQL_USER=ninja
      - MYSQL_PASSWORD=${DB_USER_PASS}
    volumes:
      - invoiceninja-database:/var/lib/mysql:rw,delegated
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=false"
    restart: unless-stopped

  invoiceninja-app:
    container_name: invoiceninja-app
    image: invoiceninja/invoiceninja:5
    security_opt:
      - no-new-privileges:true
    cap_add:
      - SYS_ADMIN
    environment: 
      - APP_URL=https://${SUBDOMAIN}.${DOMAIN}
      - APP_KEY=${APP_KEY}
      - APP_DEBUG=true
      - MULTI_DB_ENABLED=false
      - DB_HOST1=invoiceninja-db
      - DB_USERNAME1=ninja
      - DB_PASSWORD1=${DB_USER_PASS}
      - DB_DATABASE1=ninja
      - PHANTOMJS_PDF_GENERATION=false
      - SNAPPDF_EXECUTABLE_PATH="/usr/bin/chromium-browser"
    volumes:
      - public:/var/www/app/public
      - storage:/var/www/app/storage
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - invoiceninja-db
    networks: 
      - internal
    restart: unless-stopped

  invoiceninja-nginx:
    container_name: invoiceninja-nginx
    image: nginx:alpine
    security_opt:
      - no-new-privileges:true
    depends_on:
      - invoiceninja-app
    networks:
      - internal
      - proxy
    volumes:
      - public:/var/www/app/public
      - storage:/var/www/app/storage
      - ./nginx/nginx.conf:/etc/nginx/conf.d/in-vhost.conf:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.invoiceninja-nginx.entrypoints=http"
      - "traefik.http.routers.invoiceninja-nginx.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.invoiceninja-nginx.middlewares=secured@file"
      - "traefik.http.routers.invoiceninja-nginx-secure.entrypoints=https"
      - "traefik.http.routers.invoiceninja-nginx-secure.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.invoiceninja-nginx-secure.tls=true"
      - "traefik.http.routers.invoiceninja-nginx-secure.tls.certresolver=le-dns"
      - "traefik.http.routers.invoiceninja-nginx-secure.service=invoiceninja-nginx"
      - "traefik.http.services.invoiceninja-nginx.loadbalancer.server.port=80"
    restart: unless-stopped

  # invoiceninja-caddy:
  #   container_name: invoiceninja-caddy
  #   image: caddy:alpine
  #   security_opt:
  #     - no-new-privileges:true
  #   environment: 
  #     - APP_URL=http://${SUBDOMAIN}.${DOMAIN}
  #   volumes:
  #     - ./caddy/Caddyfile:/etc/caddy/Caddyfile
  #     -  public:/var/www/app/public
  #     -  storage:/var/www/app/storage
  #   depends_on:
  #     - invoiceninja-app
  #   networks:
  #     - internal
  #     - proxy
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.invoiceninja-caddy.entrypoints=http"
  #     - "traefik.http.routers.invoiceninja-caddy.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
  #     - "traefik.http.routers.invoiceninja-caddy.middlewares=secured@file"
  #     - "traefik.http.routers.invoiceninja-caddy-secure.entrypoints=https"
  #     - "traefik.http.routers.invoiceninja-caddy-secure.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
  #     - "traefik.http.routers.invoiceninja-caddy-secure.tls=true"
  #     - "traefik.http.routers.invoiceninja-caddy-secure.tls.certresolver=le-dns"
  #     - "traefik.http.routers.invoiceninja-caddy-secure.service=invoiceninja-caddy"
  #     - "traefik.http.services.invoiceninja-caddy.loadbalancer.server.port=80"
  #   restart: unless-stopped