## global definitions
global:
  domain: "privacy.box"
  storage: "/media/storage"

app:
  traefik:
    subdomain: traefik
    registrar:
      name: "transip"
      email: "john.doe@privacy.box"
    credentials:
      username: ""
      password: ""

  portainer:
    subdomain: portainer

  ampache:
  fireflyiii:
  ghost:
  gitea:
  hugo:
  invidious:
  jackett:
  jellyfin:
  jitsi-meet:
  mastodon:
  matomo:
  matrix-synapse:
  netdata:
  nextcloud:
  node-red:
  nzbget:
  pihole:
  radarr:
  rocketchat:
  sonarr:
  spotweb:
  syncthing:
  transmission:
  wallabag:
  wireguard:
  wordpress: