version: "3.3"

networks:
  proxy:
    external:
      name: proxy
  internal:
    internal: true

services:

  fireflyiii-db:
    container_name: "fireflyiii-db"
    image: "postgres:10-alpine"
    security_opt:
      - no-new-privileges:true
    environment:
      - POSTGRES_USER=firefly
      - POSTGRES_PASSWORD=secret_firefly_password
    volumes:
      - firefly_iii_db:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped

  fireflyiii-app:
    image: "jc5x/firefly-iii:latest"
    container_name" "fireflyiii-app"
    security_opt:
      - no-new-privileges:true
    volumes:
      - firefly_iii_export:/var/www/firefly-iii/storage/export
      - firefly_iii_upload:/var/www/firefly-iii/storage/upload
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fireflyiii-app.entrypoints=http"
      - "traefik.http.routers.fireflyiii-app.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.fireflyiii-app.middlewares=https-redirect@file"
      - "traefik.http.routers.fireflyiii-app-secure.entrypoints=https"
      - "traefik.http.routers.fireflyiii-app-secure.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.fireflyiii-app-secure.tls=true"
      - "traefik.http.routers.fireflyiii-app-secure.tls.certresolver=le-dns"
      - "traefik.http.routers.fireflyiii-app-secure.service=fireflyiii-app"
      - "traefik.http.services.fireflyiii-app.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
    env_file: .env
    depends_on:
      - fireflyiii-db
    restart: unless-stopped

volumes:
   firefly_iii_export:
   firefly_iii_upload:
   firefly_iii_db:
