version: "2.1"

networks:
  proxy:
    external:
      name: proxy

volumes:
  kodi-config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${STORAGE_ROOT}/docker/kodi/config
  kodi-series-dir:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${STORAGE_ROOT}/video/Series
  kodi-movies-dir:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${STORAGE_ROOT}/video/Movies
  # Example When mounting remote NFS dir:
  # kodi-series-dir:
  #   driver: local
  #   driver_opts:
  #     type: nfs4
  #     o: "addr=${NFS_REMOTE_IP},rw"
  #     device: ":${NFS_SERIES_REMOTE_PATH}"
  # kodi-movies-dir:
  #   driver: local
  #   driver_opts:
  #     type: nfs4
  #     o: "addr=${NFS_REMOTE_IP},rw"
  #     device: ":${NFS_MOVIES_REMOTE_PATH}"

services:
  kodi:
    container_name: kodi-headless
    image: linuxserver/kodi-headless:latest
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - UMASK_SET=022 #optional
    volumes:
      - kodi-config:/config/.kodi
      - kodi-series-dir:/tv
      - kodi-series-dir:/movies
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 9090:9090
      - 9777:9777/udp
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kodi.entrypoints=http"
      - "traefik.http.routers.kodi.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.kodi.middlewares=https-redirect@file"
      - "traefik.http.routers.kodi-secure.entrypoints=https"
      - "traefik.http.routers.kodi-secure.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.kodi-secure.tls=true"
      - "traefik.http.routers.kodi-secure.tls.certresolver=le-dns"
      - "traefik.http.routers.kodi-secure.service=kodi"
      - "traefik.http.services.kodi.loadbalancer.server.port=8080"
      - "traefik.docker.network=proxy"
    networks:
      - proxy
    restart: unless-stopped