version: '3.3'

networks:
  proxy:
    external: 
      name: proxy
  internal:
    internal: true

volumes:
  gitea-db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${STORAGE_ROOT}/docker/gitea/database/
  gitea-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${STORAGE_ROOT}/docker/gitea/data

services:
  gitea-db:
    container_name: "gitea-db"
    image: "mariadb"
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=secret
    labels:
      - "traefik.enable=false"
    networks:
      - internal
    volumes:
      - gitea-db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro

  gitea-app:
    container_name: "gitea-app"
    image: "gitea/gitea:latest"
    security_opt:
      - no-new-privileges:true
    volumes:
      - gitea-data:/data
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - gitea-db
    environment:
      - ROOT_URL=https://${SUBDOMAIN}.${DOMAIN}
      - DOMAIN=${SUBDOMAIN}.${DOMAIN}
      - PROTOCOL=https
      - USER_UID=1000
      - USER_GID=1000
      - DB_TYPE=mysql
      - DB_HOST=gitea-db:3306
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=secret
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitea-app.entrypoints=http"
      - "traefik.http.routers.gitea-app.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.gitea-app.middlewares=https-redirect@file"
      - "traefik.http.routers.gitea-app-secure.entrypoints=https"
      - "traefik.http.routers.gitea-app-secure.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.gitea-app-secure.tls=true"
      - "traefik.http.routers.gitea-app-secure.tls.certresolver=le-dns"
      - "traefik.http.routers.gitea-app-secure.service=gitea-app"
      - "traefik.http.services.gitea-app.loadbalancer.server.port=3000"
      - "traefik.docker.network=proxy"
    networks:
      - proxy
      - internal
    ports:
      - "222:22"
    restart: unless-stopped
