version: '3.3'

networks:
  proxy:
    external: 
      name: proxy
  internal:
    internal: true

services:

  gitea-db:
    image: mariadb
    container_name: gitea-db
    volumes:
      - gitea-db:/var/lib/mysql
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_PASSWORD=mysql
      - MYSQL_DATABASE=gitea
      - MYSQL_USER=gitea
    labels:
      - "traefik.enable=false"
    networks:
      - internal
    restart: unless-stopped

  gitea-app:
    image: gitea/gitea:latest
    container_name: gitea-app
    depends_on:
      - gitea-db
    environment:
      - ROOT_URL=https://${SUBDOMAIN}.${DOMAIN}
      - DOMAIN=${SUBDOMAIN}.${DOMAIN}
      - PROTOCOL=http
      - USER_UID=1000
      - USER_GID=1000
      - DB_TYPE=mysql
      - DB_HOST=gitea-db:3306
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=mysql
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitea-app.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.gitea-app.entrypoints=websecure"
      - "traefik.http.routers.gitea-app.tls.certresolver=myresolver"
    networks:
      - proxy
      - internal
    ports:
      - "3000:3000"
      - "222:22"
    restart: unless-stopped

volumes:
  gitea:
  gitea-db:
