version: '3.3'

networks:
  proxy:
    external: 
      name: proxy
  internal:
    internal: true

services:

  invidious-db:
    image: postgres:10
    restart: unless-stopped
    volumes:
      - postgresdata:/var/lib/postgresql/data
    labels:
      - "traefik.enable=false"
    networks:
      - proxy
      - internal

  invidious-app:
    image: flourgaz/invidious
    container_name: invidious-app
    expose:
      - "80"
    volumes:
      - ./config.yml:/invidious-app/config/config.yml
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.invidious-app.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.invidious-app.entrypoints=websecure"
      - "traefik.http.routers.invidious-app.tls.certresolver=myresolver"
    networks:
      - proxy
      - internal
    ports:
      - "3000:3000"
    depends_on:
      - invidious-db
    restart: unless-stopped

volumes: 
  postgresdata: 
    external: 
      name: invidious_postgresdata
