version: '3'

networks:
  proxy:
    external: 
      name: proxy
  internal:
    internal: true
      
volumes:
  homeassistant-config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${STORAGE_ROOT}/docker/homeassistant/config      

services:
  homeassistant-app:
    container_name: home-assistant
    image: homeassistant/home-assistant:stable
    volumes:
      - homeassistant-config:/config
    # devices:
    #   - /dev/ttyUSB0:/dev/ttyUSB0
    #   - /dev/ttyUSB1:/dev/ttyUSB1
    #   - /dev/ttyACM0:/dev/ttyACM0
    environment:
      - TZ=Europe/Amsterdam
    labels:
      - "traefik.enable=false"
    network_mode: host
    restart: always

  homeassistant-nginx:
    container_name: homeassistant-nginx
    image: nginx:alpine
    security_opt:
      - no-new-privileges:true
    depends_on:
      - homeassistant-app
    networks:
      - internal
      - proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homeassistant.entrypoints=http"
      - "traefik.http.routers.homeassistant.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.homeassistant.middlewares=https-redirect@file"
      - "traefik.http.routers.homeassistant-secure.entrypoints=https"
      - "traefik.http.routers.homeassistant-secure.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.homeassistant-secure.tls=true"
      - "traefik.http.routers.homeassistant-secure.tls.certresolver=le-dns"
      - "traefik.http.routers.homeassistant-secure.service=homeassistant"
      - "traefik.http.services.homeassistant.loadbalancer.server.port=9117"
      - "traefik.docker.network=proxy"
    restart: unless-stopped