version: '3'
      
networks:
  # Not ideal but required? for host network mode routing
  fixed:
    ipam:
      config:
        - subnet: 10.2.2.0/24

volumes:
  ha-config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${STORAGE_ROOT}/docker/homeassistant/config

  ha-mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${STORAGE_ROOT}/docker/homeassistant/database      

  ha-zigbee2mqtt-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${STORAGE_ROOT}/docker/homeassistant/zigbee2mqtt/data

  ha-mosquitto-config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${STORAGE_ROOT}/docker/homeassistant/mosquitto/config

  ha-mosquitto-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${STORAGE_ROOT}/docker/homeassistant/mosquitto/data

services:
  ha-app:
    container_name: ha-app
    image: homeassistant/home-assistant:latest
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=Europe/Amsterdam
    # Add devices if present in hardware
    # devices:
    #   - /dev/ttyUSB1:/dev/ttyUSB1
    #   - /dev/ttyRFXCOM:/dev/ttyRFXCOM 
    volumes:
      - ha-config:/config
      - /sys/class/thermal:/sys/class/thermal
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=false"
    depends_on:
      - ha-mariadb
      - ha-mqtt
      # - ha-zigbee2mqtt
    network_mode: host
    restart: unless-stopped

  ha-mqtt:
    container_name: ha-mqtt
    image: eclipse-mosquitto:latest
    security_opt:
      - no-new-privileges:true
    volumes:
      - ha-mosquitto-config:/mosquitto/config
      - ha-mosquitto-data:/mosquitto/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "1883:1883"
    environment:
      - TZ=Europe/Amsterdam
    labels:
      - "traefik.enable=false"
    networks:
      fixed:
        ipv4_address: 10.2.2.20
    restart: unless-stopped

  # # Optional if working with a ZigBee adapter
  # ha-zigbee2mqtt:
  #   container_name: ha-zigbee2mqtt
  #   image: koenkk/zigbee2mqtt:latest
  #   security_opt:
  #     - no-new-privileges:true
  #   depends_on:
  #     - ha-mqtt
  #   environment:
  #     - TZ=Europe/Amsterdam
  #   volumes:
  #     - ha-zigbee2mqtt-data:/app/data
  #     # Optional: only required for auto-detecting port
  #     # - /run/udev:/run/udev:ro
  #     - /etc/localtime:/etc/localtime:ro
  #   # Add devices if present in hardware
  #   # devices:
  #   #   - /dev/ttyZigbeeUSB:/dev/ttyZigbeeUSB
  #   labels:
  #     - "traefik.enable=false"
  #   # Only required for auto-detecting port
  #   # network_mode: host
  #   # Only required if mqtt server is not on shared network
  #   # privileged: true
  #   networks:
  #     fixed:
  #       ipv4_address: 10.2.2.21
  #   restart: unless-stopped

  ha-mariadb:
    container_name: ha-mariadb
    image: mariadb:latest
    security_opt:
      - no-new-privileges:true
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
      - MYSQL_DATABASE=homeassistant
      - MYSQL_USER=homeassistant
      - MYSQL_PASSWORD=${DB_USER_PASS}
      - TZ=Europe/Amsterdam
    volumes:
      - ha-mariadb:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    networks:
      fixed:
        ipv4_address: 10.2.2.22
    ports:
      - "3306:3306"
    labels:
      - "traefik.enable=false"
    restart: unless-stopped