version: "3.3"

networks:
  proxy:
    external: 
      name: proxy

volumes:
  pihole-config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${STORAGE_ROOT}/docker/pihole/etc/
  pihole-dnsmasq:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${STORAGE_ROOT}/docker/pihole/dnsmasq/

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    security_opt:
      - no-new-privileges:true
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
    environment:
      - TZ=Europe/Amsterdam
      - WEBPASSWORD=${ADMIN_PASS}
      - VIRTUAL_HOST=https://${SUBDOMAIN}.${DOMAIN}
      - DNS1=1.1.1.1
      - DNS2=1.0.0.1
    volumes:
      - 'pihole-config:/etc/pihole/'
      - 'pihole-dnsmasq:/etc/dnsmasq.d/'
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.entrypoints=http"
      - "traefik.http.routers.pihole.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.pihole.middlewares=https-redirect@file"
      - "traefik.http.routers.pihole-secure.entrypoints=https"
      - "traefik.http.routers.pihole-secure.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.pihole-secure.tls=true"
      - "traefik.http.routers.pihole-secure.tls.certresolver=le-dns"
      - "traefik.http.routers.pihole-secure.service=pihole"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
    networks:
      - proxy
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN
    restart: unless-stopped