version: '3'  

services:

  nextcloud-db:
    image: mariadb
    container_name: nextcloud-db
    volumes:
      - nextcloud-db:/var/lib/mysql
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_PASSWORD=mysql
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    restart: unless-stopped

  nextcloud-redis:
    image: redis:alpine
    container_name: nextcloud-redis
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  nextcloud-app:
    image: nextcloud:latest
    container_name: nextcloud-app
    expose:
      - 80
    depends_on:
      - nextcloud-db
      - nextcloud-redis
    volumes:
      - nextcloud:/var/www/html
      - ./app/config:${CONFIG_STORAGE_PATH}
      - ./app/custom_apps:${APPS_STORAGE_PATH}
      - ./app/data:${DATA_STORAGE_PATH}
      - ./app/themes:${THEME_STORAGE_PATH}
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - VIRTUAL_HOST=${SUBDOMAIN}.${DOMAIN}
      - LETSENCRYPT_HOST=${SUBDOMAIN}.${DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - MYSQL_HOST=nextcloud-db:3306
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=mysql
    restart: unless-stopped

volumes:
  nextcloud:
  nextcloud-db:
  nextcloud-redis:

networks:
  default:
    external:
      name: nginx-proxy
