version: '3'  

services:

  nextcloud-db:
    image: mariadb
    container_name: nextcloud-mariadb
    volumes:
      - nextcloud-db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_PASSWORD=mysql
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    restart: unless-stopped

  nextcloud-app:
    image: nextcloud:latest
    container_name: nextcloud-app
    expose:
      - 80
    depends_on:
      - nextcloud-db
    volumes:
      - nextcloud:/var/www/html
      - ./app/config:/var/www/html/config
      - ./app/custom_apps:/var/www/html/custom_apps
      - ./app/data:/var/www/html/data
      - ./app/themes:/var/www/html/themes
      - /etc/localtime:/etc/localtime:ro
    environment:
      - VIRTUAL_HOST=${SUBDOMAIN}.${DOMAIN}
      - LETSENCRYPT_HOST=${SUBDOMAIN}.${DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    restart: unless-stopped

volumes:
  nextcloud:
  nextcloud-db:

networks:
  default:
    external:
      name: nginx-proxy
