version: "3.3"

networks:
  proxy:
    external: 
      name: proxy
  internal:
    internal: true

services:

  nextcloud-db:
    image: mariadb
    container_name: nextcloud-db
    volumes:
      - nextcloud-db:/var/lib/mysql
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_PASSWORD=mysql
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    labels:
      - "traefik.enable=false"
    networks:
      - internal
    restart: unless-stopped

  nextcloud-redis:
    image: redis:alpine
    container_name: nextcloud-redis
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=false"
    networks:
      - internal

  nextcloud-app:
    image: nextcloud:latest
    container_name: nextcloud-app
    expose:
      - "80"
    depends_on:
      - nextcloud-db
      - nextcloud-redis
    volumes:
      - nextcloud:/var/www/html
      - ./app/config:${CONFIG_STORAGE_PATH}
      - ./app/custom_apps:${APPS_STORAGE_PATH}
      - ./app/data:${DATA_STORAGE_PATH}
      - ./app/themes:${THEME_STORAGE_PATH}
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_HOST=nextcloud-db:3306
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=mysql
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud-app.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.nextcloud-app.entrypoints=websecure"
      - "traefik.http.routers.nextcloud-app.tls.certresolver=myresolver"
    networks:
      - proxy
      - internal
    restart: unless-stopped

volumes:
  nextcloud:
  nextcloud-db:
  nextcloud-redis:
