version: "3.3"

networks:
  proxy:
    external: 
      name: proxy
  internal:
    internal: true

volumes:
  nextcloud-app:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./app
  nextcloud-config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${STORAGE_ROOT}/docker/nextcloud/config
  nextcloud-custom-apps:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${STORAGE_ROOT}/docker/nextcloud/apps
  nextcloud-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${STORAGE_ROOT}/nextcloud-data
  nextcloud-db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${STORAGE_ROOT}/docker/nextcloud/database/
 
services:
  nextcloud-db:
    container_name: nextcloud-db
    image: mariadb
    security_opt:
      - no-new-privileges:true
    networks:
      - internal
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=${DB_USER_PASS}
    volumes:
      - nextcloud-db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=false"
    restart: unless-stopped

  nextcloud-fpm:
    container_name: nextcloud-fpm
    image: nextcloud:fpm-alpine
    security_opt:
      - no-new-privileges:true
    depends_on:
      - nextcloud-db
      - nextcloud-redis
    networks:
      - internal
    environment:
      - MYSQL_HOST=nextcloud-db
      - MYSQL_PASSWORD=${DB_USER_PASS}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    volumes:
      - nextcloud-app:/var/www/html
      - nextcloud-custom-apps:/var/www/html/custom_apps
      - nextcloud-config:/var/www/html/config
      - nextcloud-data:/var/www/html/data
      - ${STORAGE_ROOT}/docker/nextcloud/log/nextcloud.log:/var/www/html/data/nextcloud.log
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=false"
    restart: unless-stopped

  nextcloud-nginx:
    container_name: nextcloud-nginx
    image: nginx:alpine
    security_opt:
      - no-new-privileges:true
    depends_on:
      - nextcloud-fpm
    networks:
      - internal
      - proxy
    volumes:
      - nextcloud-app:/var/www/html:ro
      - nextcloud-custom-apps:/var/www/html/custom_apps:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro 
      - ./logs/nginx:/var/log/nginx
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud-nginx.entrypoints=http"
      - "traefik.http.routers.nextcloud-nginx.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.nextcloud-nginx.middlewares=https-redirect@file"
      - "traefik.http.middlewares.nc-rep.redirectregex.regex=https://(.*)/.well-known/(card|cal)dav"
      - "traefik.http.middlewares.nc-rep.redirectregex.replacement=https://$$1/remote.php/dav/"
      - "traefik.http.middlewares.nc-rep.redirectregex.permanent=true"
      - "traefik.http.middlewares.nc-header.headers.customFrameOptionsValue=SAMEORIGIN"
      - "traefik.http.routers.nextcloud-nginx.middlewares=nc-rep,nc-header"
      - "traefik.http.routers.nextcloud-nginx-secure.entrypoints=https"
      - "traefik.http.routers.nextcloud-nginx-secure.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.nextcloud-nginx-secure.tls=true"
      - "traefik.http.routers.nextcloud-nginx-secure.tls.certresolver=le-dns"
      - "traefik.http.routers.nextcloud-nginx-secure.service=nextcloud-nginx"
      - "traefik.http.services.nextcloud-nginx.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
    restart: unless-stopped

  nextcloud-redis:
    container_name: nextcloud-redis
    image: redis:alpine
    security_opt:
      - no-new-privileges:true
    networks: 
      - internal
    volumes:
      - ./nextcloud-redis:/data
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=false"
    restart: unless-stopped

  nextcloud-cron:
    container_name: nextcloud-cron
    image: nextcloud:fpm-alpine
    security_opt:
      - no-new-privileges:true
    depends_on:
      - nextcloud-db
      - nextcloud-fpm
      - nextcloud-redis
    entrypoint: /cron.sh
    networks:
      - internal
    volumes:
      - nextcloud-app:/var/www/html
      - nextcloud-custom-apps:/var/www/html/custom_apps
      - nextcloud-config:/var/www/html/config
      - nextcloud-data/data
      - ${STORAGE_ROOT}/docker/nextcloud/log/nextcloud.log:/var/www/html/data/nextcloud.log
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=false"
    restart: unless-stopped