version: '3.3'

networks:
  proxy:
    external: 
      name: proxy

services:
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - ${STORAGE_ROOT}/docker/jackett/config:/config
      - ${STORAGE_ROOT}/docker/jackett/downloads:/downloads
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jackett.entrypoints=http"
      - "traefik.http.routers.jackett.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.jackett.middlewares=https-redirect@file"
      - "traefik.http.routers.jackett-secure.entrypoints=https"
      - "traefik.http.routers.jackett-secure.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.jackett-secure.tls=true"
      - "traefik.http.routers.jackett-secure.tls.certresolver=http"
      - "traefik.http.routers.jackett-secure.service=jackett"
      - "traefik.http.services.jackett.loadbalancer.server.port=9117"
      - "traefik.docker.network=proxy"
    # ports:
    #   - 9117
    networks:
      - proxy
    restart: unless-stopped
