version: '3.3'

networks:
  proxy:
    external: 
      name: proxy

services:
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./app/config:/config
      - ./app/downloads:/downloads
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jackett.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.jackett.entrypoints=websecure"
      - "traefik.http.routers.jackett.tls.certresolver=myresolver"
    networks:
      - proxy
    ports:
      - "9117:9117"
    restart: unless-stopped
