# version: '2'

# networks:
#   proxy:
#     external:
#       name: proxy
#   internal:
#     internal: true

# volumes:
#   spotweb-config:
#     driver: local
#     driver_opts:
#       type: none
#       o: bind
#       device: ${STORAGE_ROOT}/docker/spotweb/config
#   spotweb-downloads:
#     driver: local
#     driver_opts:
#       type: none
#       o: bind
#       device: ${STORAGE_ROOT}/docker/spotweb/downloads

# services:
#   spotweb-db:
#     container_name: spotweb-db
#     image: mariadb
#     security_opt:
#       - no-new-privileges:true
#     networks: 
#       - internal
#     environment:
#       MYSQL_ROOT_PASSWORD: 123
#       MYSQL_USER: spotweb
#       MYSQL_PASSWORD: spotweb
#       MYSQL_DATABASE: spotweb
#     volumes:
#       - /etc/localtime:/etc/localtime:ro
#     labels:
#       - "traefik.enable=false"
#     restart: unless-stopped    

#   spotweb-app:
#     container_name: spotweb-app
#     image: erikdevries/spotweb
#     security_opt:
#       - no-new-privileges:true
#     # command: sed -i 's+= $$nwsetting+= "https://beta-spotweb.dropdoos.nl"+g' /var/www/spotweb/settings.php >/dev/null 2>&1
#     depends_on:
#       - spotweb-db
#     volumes:
#       - /etc/localtime:/etc/localtime:ro
#     environment:
#       - TZ=Europe/Amsterdam
#       - SPOTWEB_DB_TYPE=pdo_mysql
#       - SPOTWEB_DB_HOST=spotweb-db
#       - SPOTWEB_DB_PORT=3306
#       - SPOTWEB_DB_USER=spotweb
#       - SPOTWEB_DB_PASS=${DB_USER_PASS}
#       - SPOTWEB_CRON_RETRIEVE=*/15 * * * *
#       - SPOTWEB_CRON_CACHE_CHECK=10 */1 * * *
#     labels:
#       - "traefik.enable=true"
#       - "traefik.http.routers.spotweb.entrypoints=http"
#       - "traefik.http.routers.spotweb.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
#       - "traefik.http.routers.spotweb.middlewares=https-redirect@file"
#       - "traefik.http.routers.spotweb-secure.entrypoints=https"
#       - "traefik.http.routers.spotweb-secure.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
#       - "traefik.http.routers.spotweb-secure.tls=true"
#       - "traefik.http.routers.spotweb-secure.tls.certresolver=le-dns"
#       - "traefik.http.routers.spotweb-secure.service=spotweb"
#       - "traefik.http.services.spotweb.loadbalancer.server.port=80"
#       - "traefik.docker.network=proxy"
#     networks:
#       - proxy
#       - internal
#     restart: unless-stopped





version: "3.3"

networks:
  proxy:
    external:
      name: proxy
  internal:
    internal: true

volumes:
  spotweb-database:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${STORAGE_ROOT}/docker/spotweb/database

services:
  spotweb-mariadb:
    container_name: "spotweb-mariadb"
    image: "mariadb"
    security_opt:
      - no-new-privileges:true
    networks:
      - internal
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
      - MYSQL_DATABASE=spotweb
      - MYSQL_USER=spotweb
      - MYSQL_PASSWORD=${DB_USER_PASS}
    volumes:
      - spotweb-database:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=false"
    restart: unless-stopped

  spotweb-app:
    container_name: "spotweb-app"
    image: "jgeusebroek/spotweb:latest"
    security_opt:
      - no-new-privileges:true
    # command: sed -i 's+= $$nwsetting+= "https://beta-spotweb.dropdoos.nl"+g' /var/www/spotweb/settings.php >/dev/null 2>&1
    depends_on:
      - spotweb-mariadb
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Europe/Amsterdam
      - SPOTWEB_DB_TYPE=pdo_mysql
      - SPOTWEB_DB_HOST=spotweb-mariadb
      - SPOTWEB_DB_PORT=3306
      - SPOTWEB_DB_USER=spotweb
      - SPOTWEB_DB_PASS=${DB_USER_PASS}
      - SPOTWEB_CRON_RETRIEVE=*/15 * * * *
      - SPOTWEB_CRON_CACHE_CHECK=10 */1 * * *
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.spotweb.entrypoints=http"
      - "traefik.http.routers.spotweb.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.spotweb.middlewares=https-redirect@file"
      - "traefik.http.routers.spotweb-secure.entrypoints=https"
      - "traefik.http.routers.spotweb-secure.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.spotweb-secure.tls=true"
      - "traefik.http.routers.spotweb-secure.tls.certresolver=le-dns"
      - "traefik.http.routers.spotweb-secure.service=spotweb"
      - "traefik.http.services.spotweb.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
    networks:
      - proxy
      - internal
    restart: unless-stopped