version: "3.3"

networks:
  proxy:
    external: 
      name: proxy
  internal:
    internal: true

services:
  wp-site1-db:
    image: mariadb
    container_name: wp-site1-db
    volumes:
      - wp-site1-db:/var/lib/mysql
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=false"
    networks:
      - internal
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    restart: always

  wp-site1-app:
    depends_on:
      - wp-site1-db
    image: wordpress:latest
    container_name: wp-site1-app
    expose:
      - "80"
    environment:
      - WORDPRESS_DB_HOST=wp-site1-db:3306
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wp-site1-app.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.wp-site1-app.entrypoints=websecure"
      - "traefik.http.routers.wp-site1-app.tls.certresolver=myresolver"
    networks:
      - proxy
      - internal
    restart: always

volumes:
  wp-site1-db:
