version: "3.3"

networks:
  proxy:
    external: 
      name: proxy
  internal:
    internal: true

services:
  wp-site1-db:
    container_name: "wp-site1-db"
    image: "mariadb"
    security_opt:
      - no-new-privileges:true
    volumes:
      - wp-site1-db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=false"
    networks:
      - internal
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    restart: unless-stopped

  wp-site1-app:
    container_name: "wp-site1-app"
    image: "wordpress:latest"
    security_opt:
      - no-new-privileges:true
    depends_on:
      - wp-site1-db
    environment:
      - WORDPRESS_DB_HOST=wp-site1-db:3306
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
    volumes:
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wp-site1-app.entrypoints=http"
      - "traefik.http.routers.wp-site1-app.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.wp-site1-app.middlewares=https-redirect@file"
      - "traefik.http.routers.wp-site1-app-secure.entrypoints=https"
      - "traefik.http.routers.wp-site1-app-secure.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.wp-site1-app-secure.tls=true"
      - "traefik.http.routers.wp-site1-app-secure.tls.certresolver=le-dns"
      - "traefik.http.routers.wp-site1-app-secure.service=wp-site1-app"
      - "traefik.http.services.wp-site1-app.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
    networks:
      - proxy
      - internal
    restart: unless-stopped

volumes:
  wp-site1-db:
