version: "3.3"

networks:
  proxy:
    external: 
      name: proxy
  internal:
    internal: true

services:
  wp-db:
    container_name: "wp-${COMPOSE_PROJECT_NAME}-db"
    image: "mariadb"
    security_opt:
      - no-new-privileges:true
    volumes:
      - ${STORAGE_ROOT}/docker/wordpress/${COMPOSE_PROJECT_NAME}/database:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=false"
    networks:
      - internal
    environment:
      - DB_ROOT_PASSWORD=${DB_ROOT_PASS}
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=${DB_USER_PASS}
    restart: unless-stopped

  wp-app:
    container_name: "wp-${COMPOSE_PROJECT_NAME}-app"
    image: "wordpress:latest"
    security_opt:
      - no-new-privileges:true
    depends_on:
      - wp-db
    environment:
      - WORDPRESS_DB_HOST=wp-db:3306
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=${DB_USER_PASS}
    volumes:
      - ${STORAGE_ROOT}/docker/wordpress/${COMPOSE_PROJECT_NAME}/plugins:/var/www/html/wp-content/plugins/
      - ${STORAGE_ROOT}/docker/wordpress/${COMPOSE_PROJECT_NAME}/themes:/var/www/html/wp-content/themes/
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-app.entrypoints=http"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-app.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-app.middlewares=https-redirect@file"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-app-secure.entrypoints=https"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-app-secure.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-app-secure.tls=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-app-secure.tls.certresolver=le-dns"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-app-secure.service=${COMPOSE_PROJECT_NAME}-app"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}-app.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
    networks:
      - proxy
      - internal
    restart: unless-stopped

volumes:
  wp-db:
