version: "3.3"

networks:
  proxy:
    external: 
      name: proxy
  internal:
    internal: true

services:
  ${WP_INSTANCE_NAME}-db:
    container_name: "${WP_INSTANCE_NAME}-db"
    image: "mariadb"
    security_opt:
      - no-new-privileges:true
    volumes:
      - ${STORAGE_ROOT}/docker/wordpress/${WP_INSTANCE_NAME}/database:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=false"
    networks:
      - internal
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASS}
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=${MYSQL_USER_PASS}
    restart: unless-stopped

  ${WP_INSTANCE_NAME}-app:
    container_name: "${WP_INSTANCE_NAME}-app"
    image: "wordpress:latest"
    security_opt:
      - no-new-privileges:true
    depends_on:
      - ${WP_INSTANCE_NAME}-db
    environment:
      - WORDPRESS_DB_HOST=${WP_INSTANCE_NAME}-db:3306
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=${MYSQL_USER_PASS}
    volumes:
      - ${STORAGE_ROOT}/docker/wordpress/${WP_INSTANCE_NAME}/plugins:/var/www/html/wp-content/plugins/
      - ${STORAGE_ROOT}/docker/wordpress/${WP_INSTANCE_NAME}/themes:/var/www/html/wp-content/themes/
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wp-site1-app.entrypoints=http"
      - "traefik.http.routers.wp-site1-app.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.wp-site1-app.middlewares=https-redirect@file"
      - "traefik.http.routers.wp-site1-app-secure.entrypoints=https"
      - "traefik.http.routers.wp-site1-app-secure.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.wp-site1-app-secure.tls=true"
      - "traefik.http.routers.wp-site1-app-secure.tls.certresolver=le-dns"
      - "traefik.http.routers.wp-site1-app-secure.service=wp-site1-app"
      - "traefik.http.services.wp-site1-app.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
    networks:
      - proxy
      - internal
    restart: unless-stopped

volumes:
  wp-site1-db:
