version: '3.3'

networks:
  proxy:
    external: 
      name: proxy
  internal:
    internal: true

services:

  ampache-db:
    image: mariadb
    container_name: ampache-db
    volumes:
      - ampache-db:/var/lib/mysql
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=false"
    networks:
      - internal
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_PASSWORD=mysql
      - MYSQL_DATABASE=ampache
      - MYSQL_USER=ampache
    restart: unless-stopped

  ampache-app:
    image: ampache/ampache:latest
    container_name: ampache-app
    depends_on:
      - ampache-db
    volumes:
      # - ./path/to/media/files:/media:ro
      - ./data/mysql:/var/lib/mysql
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ampache-app.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.ampache-app.entrypoints=websecure"
      - "traefik.http.routers.ampache-app.tls.certresolver=myresolver"
      - "traefik.docker.network=proxy"
    networks:
      - proxy
      - internal
    restart: unless-stopped

volumes:
  ampache:
  ampache-db:
