version: "2.1"

networks:
  proxy:
    external:
      name: proxy

volumes:
  nzbget-config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${STORAGE_ROOT}/docker/nzbget/config
  nzbget-downloads:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${STORAGE_ROOT}/downloads

services:
  nzbget-vpn:
    container_name: nzbget-vpn
    image: xblackbytesx/expressvpn:latest
    security_opt:
      - no-new-privileges:true
    environment:
      - ACTIVATION_CODE=${VPN_ACTIVATION_CODE}
      - SERVER=${VPN_SERVER}
    cap_add:
      - NET_ADMIN
    devices: 
      - /dev/net/tun
    stdin_open: true
    tty: true
    command: /bin/bash
    privileged: true
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nzbget-vpn.entrypoints=http"
      - "traefik.http.routers.nzbget-vpn.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.nzbget-vpn.middlewares=secured@file"
      - "traefik.http.routers.nzbget-vpn-secure.entrypoints=https"
      - "traefik.http.routers.nzbget-vpn-secure.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.nzbget-vpn-secure.tls=true"
      - "traefik.http.routers.nzbget-vpn-secure.tls.certresolver=le-dns"
      - "traefik.http.routers.nzbget-vpn-secure.service=nzbget-vpn"
      - "traefik.http.services.nzbget-vpn.loadbalancer.server.port=6789"         
    restart: unless-stopped

  nzbget:
    container_name: nzbget
    image: linuxserver/nzbget:latest
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - nzbget-config:/config
      - nzbget-downloads:/downloads
      - /etc/localtime:/etc/localtime:ro
    # If NOT using the above VPN service uncomment the section below:
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.nzbget.entrypoints=http"
    #   - "traefik.http.routers.nzbget.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
    #   - "traefik.http.routers.nzbget.middlewares=secured@file"
    #   - "traefik.http.routers.nzbget-secure.entrypoints=https"
    #   - "traefik.http.routers.nzbget-secure.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
    #   - "traefik.http.routers.nzbget-secure.tls=true"
    #   - "traefik.http.routers.nzbget-secure.tls.certresolver=le-dns"
    #   - "traefik.http.routers.nzbget-secure.service=nzbget"
    #   - "traefik.http.services.nzbget.loadbalancer.server.port=6789"
    # networks:
    #   - proxy
    network_mode: service:nzbget-vpn
    depends_on:
      - nzbget-vpn
    restart: unless-stopped