version: '3.3'

networks:
  proxy:
    external: 
      name: proxy

volumes:
  volumio-config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${STORAGE_ROOT}/docker/volumio/config
  volumio-music:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${STORAGE_ROOT}/docker/volumio/music

services:
  volumio:
    container_name: volumio
    image: jbonjean/volumio:latest
    security_opt:
      - no-new-privileges:true
    environment:
      - HOST=${SUBDOMAIN}.${DOMAIN}
      # - PULSE_SERVER=unix:/pulse/native
      # - PULSE_COOKIE_DATA="$(cat $HOME/.config/pulse/cookie)"
      # - HOST_USER=$(id -u):$(id -g)
      # - AUDIO_OUTPUT=pulse
    volumes:
      - volumio-config:/data
      - volumio-music:/var/lib/mpd/music/:ro 
      # - $(readlink $HOME/.config/pulse/$(cat /etc/machine-id)-runtime):/pulse:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.volumio.entrypoints=http"
      - "traefik.http.routers.volumio.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.volumio.middlewares=https-redirect@file"
      - "traefik.http.routers.volumio-secure.entrypoints=https"
      - "traefik.http.routers.volumio-secure.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.volumio-secure.tls=true"
      - "traefik.http.routers.volumio-secure.tls.certresolver=le-dns"
      - "traefik.http.routers.volumio-secure.service=volumio"
      - "traefik.http.services.volumio.loadbalancer.server.port=3000"
      - "traefik.docker.network=proxy"
    networks:
      - proxy
    restart: unless-stopped