version: "3.3"

networks:
  proxy:
    external:
      name: proxy
  internal:
    internal: true

services:

  portainer:
    image: portainer/portainer:latest
    container_name: portainer
    command: --no-analytics
    environment:
      - TZ=Europe/Amsterdam
      - UMASK_SET=022
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    ports:
      - "9000:9000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.tls.certresolver=myresolver"
      - "traefik.docker.network=proxy"
      - "traefik.port=9000"
    networks:
      - proxy
      - internal
    restart: always
