version: '2'

services:

  ghost:
    image: ghost:latest
    volumes:
      - ghostdata:/var/lib/ghost/content
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - url=${SUBDOMAIN}.${DOMAIN}
      - database__client=mysql
      - database__connection__host=ghost-db
      - database__connection__user=ghost
      - database__connection__password=mysql
      - database__connection__database=ghost
      - VIRTUAL_HOST=${SUBDOMAIN}.${DOMAIN}
      - LETSENCRYPT_HOST=${SUBDOMAIN}.${DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - VIRTUAL_PORT=2368
    ports:
      - "2368:80"
    expose:
      - "80"
    depends_on:
      - ghost-db
    restart: unless-stopped

  ghost-db:
    image: mariadb
    volumes:
      - ghostdb:/var/lib/mysql
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=ghost
      - MYSQL_USER=ghost
      - MYSQL_PASSWORD=mysql
    restart: unless-stopped

volumes:
  ghostdb:
  ghostdata:

networks:
  default:
    external:
      name: nginx-proxy
