version: "3.3"

networks:
  proxy:
    external: 
      name: proxy
  internal:
    internal: true

services:

  ghost-db:
    container_name: "ghost-db"
    image: "mariadb"
    volumes:
      - ${STORAGE_ROOT}/docker/ghost/database:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
      - MYSQL_DATABASE=ghost
      - MYSQL_USER=ghost
      - MYSQL_PASSWORD=${DB_USER_PASS}
    labels:
      - "traefik.enable=false"
    networks:
      - internal
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      interval: 15s
      retries: 30
    restart: unless-stopped

  ghost:
    container_name: "ghost-app"
    image: "ghost:alpine"
    volumes:
      - ${STORAGE_ROOT}/docker/ghost/data:/var/lib/ghost/content
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ghost.entrypoints=http"
      - "traefik.http.routers.ghost.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.ghost.middlewares=secured@file"
      - "traefik.http.routers.ghost-secure.entrypoints=https"
      - "traefik.http.routers.ghost-secure.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.ghost-secure.tls=true"
      - "traefik.http.routers.ghost-secure.tls.certresolver=le-dns"
      - "traefik.http.routers.ghost-secure.service=ghost"
      - "traefik.http.services.ghost.loadbalancer.server.port=2368"
    environment:
      - url=https://${SUBDOMAIN}.${DOMAIN}
      - database__client=mysql
      - database__connection__host=ghost-db
      - database__connection__user=ghost
      - database__connection__password=${DB_USER_PASS}
      - database__connection__database=ghost
    networks:
      - proxy
      - internal
    depends_on:
      - ghost-db
    restart: unless-stopped

volumes:
  ghostdb:
  ghostdata:
