version: "3.3"

networks:
  proxy:
    external: 
      name: proxy
  internal:
    internal: true

services:

  ghost-db:
    container_name: "ghost-db"
    image: "mariadb"
    volumes:
      - ghostdb:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=ghost
      - MYSQL_USER=ghost
      - MYSQL_PASSWORD=mysql
    labels:
      - "traefik.enable=false"
    networks:
      - internal
    restart: unless-stopped

  ghost:
    container_name: "ghost-app"
    image: "ghost:latest"
    volumes:
      - ghostdata:/var/lib/ghost/content
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ghost.entrypoints=http"
      - "traefik.http.routers.ghost.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.ghost.middlewares=https-redirect@file"
      - "traefik.http.routers.ghost-secure.entrypoints=https"
      - "traefik.http.routers.ghost-secure.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.ghost-secure.tls=true"
      - "traefik.http.routers.ghost-secure.tls.certresolver=le-dns"
      - "traefik.http.routers.ghost-secure.service=ghost"
      - "traefik.http.services.ghost.loadbalancer.server.port=2368"
      - "traefik.docker.network=proxy"
    environment:
      - url=https://${SUBDOMAIN}.${DOMAIN}
      - database__client=mysql
      - database__connection__host=ghost-db
      - database__connection__user=ghost
      - database__connection__password=mysql
      - database__connection__database=ghost
    networks:
      - proxy
      - internal
    depends_on:
      - ghost-db
    restart: unless-stopped

volumes:
  ghostdb:
  ghostdata:
