version: "3.3"

networks:
  proxy:
    external: 
      name: proxy
  internal:
    internal: true

services:

  ghost-db:
    image: mariadb
    volumes:
      - ghostdb:/var/lib/mysql
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=ghost
      - MYSQL_USER=ghost
      - MYSQL_PASSWORD=mysql
    labels:
      - "traefik.enable=false"
    networks:
      - internal
    restart: unless-stopped

  ghost:
    image: ghost:latest
    volumes:
      - ghostdata:/var/lib/ghost/content
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ghost.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.ghost.entrypoints=websecure"
      - "traefik.http.routers.ghost.tls.certresolver=myresolver"
      - "traefik.docker.network=proxy"
      - "traefik.port=2368"
    environment:
      - url=https://${SUBDOMAIN}.${DOMAIN}
      - database__client=mysql
      - database__connection__host=ghost-db
      - database__connection__user=ghost
      - database__connection__password=mysql
      - database__connection__database=ghost
    networks:
      - proxy
      - internal
    depends_on:
      - ghost-db
    restart: unless-stopped

volumes:
  ghostdb:
  ghostdata:
