version: '3'

networks:
  proxy:
    external:
      name: proxy

volumes:
  freshrss-config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${STORAGE_ROOT}/docker/freshrss/config

services:
  freshrss:
    container_name: freshrss
    image: linuxserver/freshrss:latest
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - freshrss-config:/config
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.freshrss.entrypoints=http"
      - "traefik.http.routers.freshrss.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.freshrss.middlewares=secured@file"
      - "traefik.http.routers.freshrss-secure.entrypoints=https"
      - "traefik.http.routers.freshrss-secure.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.freshrss-secure.tls=true"
      - "traefik.http.routers.freshrss-secure.tls.certresolver=le-dns"
      - "traefik.http.routers.freshrss-secure.service=freshrss"
      - "traefik.http.services.freshrss.loadbalancer.server.port=80"
    networks:
      - proxy
    # # Used for SSH remoteForward
    # ports:
    #   - 4007:80
    restart: unless-stopped