version: "3.3"

networks:
  proxy:
    external: 
      name: proxy
  internal:
    internal: true

services:

  matomo-db:
    image: mariadb
    container_name: matomo-db
    security_opt:
      - no-new-privileges:true
    command: --max-allowed-packet=64MB
    restart: always
    volumes:
      - matomo-db:/var/lib/mysql
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=false"
    networks:
      - internal
    environment:
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=matomo
      - MYSQL_USER=matomo

  matomo-app:
    image: matomo:fpm-alpine
    container_name: matomo-app
    security_opt:
      - no-new-privileges:true
    restart: always
    depends_on:
      - matomo-db
    volumes:
      # - ./config:/var/www/html/config:rw
      # - ./logs:/var/www/html/logs
      - matomo-app:/var/www/html
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=false"
    networks:
      - internal
    environment:
      - MATOMO_DATABASE_HOST=matomo-db
      - MATOMO_DATABASE_ADAPTER=mysql
      - MATOMO_DATABASE_TABLES_PREFIX=matomo_
      - MATOMO_DATABASE_USERNAME=matomo
      - MATOMO_DATABASE_PASSWORD=secret
      - MATOMO_DATABASE_DBNAME=matomo

  matomo-nginx:
    image: nginx:alpine
    container_name: matomo-nginx
    restart: always
    volumes:
      - matomo-app:/var/www/html:ro
      - ./matomo.conf:/etc/nginx/conf.d/default.conf:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.matomo-nginx.entrypoints=http"
      - "traefik.http.routers.matomo-nginx.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.matomo-nginx.middlewares=https-redirect@file"
      - "traefik.http.routers.matomo-nginx-secure.entrypoints=https"
      - "traefik.http.routers.matomo-nginx-secure.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.matomo-nginx-secure.tls=true"
      - "traefik.http.routers.matomo-nginx-secure.tls.certresolver=http"
      - "traefik.http.routers.matomo-nginx-secure.service=matomo-nginx"
      - "traefik.http.services.matomo-nginx.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
    networks:
      - proxy
      - internal

volumes:
  matomo-db:
  matomo-app:
