version: "2.1"

networks:
  proxy:
    external:
      name: proxy

services:
  transmission:
    container_name: transmission
    image: linuxserver/transmission:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - TRANSMISSION_WEB_HOME=/combustion-release/
      - USER=${TRANSMISSION_USER}
      - PASS=${TRANSMISSION_PASS}
    volumes:
      - ${STORAGE_ROOT}/docker/transmission/config:/config
      - ${STORAGE_ROOT}/docker/transmission/downloads:/downloads
      - ${STORAGE_ROOT}/docker/transmission/watch:/watch
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.transmission.entrypoints=http"
      - "traefik.http.routers.transmission.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.transmission.middlewares=https-redirect@file"
      - "traefik.http.routers.transmission-secure.entrypoints=https"
      - "traefik.http.routers.transmission-secure.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.transmission-secure.tls=true"
      - "traefik.http.routers.transmission-secure.tls.certresolver=le-dns"
      - "traefik.http.routers.transmission-secure.service=transmission"
      - "traefik.http.services.transmission.loadbalancer.server.port=9091"
      - "traefik.docker.network=proxy"
    networks:
      - proxy
    ports:
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped