version: "2.1"

networks:
  proxy:
    external:
      name: proxy

volumes:
  transmission-config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${STORAGE_ROOT}/docker/transmission/config
  transmission-downloads:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${STORAGE_ROOT}/downloads
  transmission-watchdir:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${STORAGE_ROOT}/docker/transmission/watch

services:
  transmission-vpn:
    container_name: transmission-vpn
    image: xblackbytesx/expressvpn:latest
    security_opt:
      - no-new-privileges:true
    environment:
      - ACTIVATION_CODE=${VPN_ACTIVATION_CODE}
      - SERVER=${VPN_SERVER}
    cap_add:
      - NET_ADMIN
    devices: 
      - /dev/net/tun
    stdin_open: true
    tty: true
    command: /bin/bash
    privileged: true
    ports:
      - 51413:51413
      - 51413:51413/udp
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.transmission-vpn.entrypoints=http"
      - "traefik.http.routers.transmission-vpn.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.transmission-vpn.middlewares=secured@file"
      - "traefik.http.routers.transmission-vpn-secure.entrypoints=https"
      - "traefik.http.routers.transmission-vpn-secure.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.transmission-vpn-secure.tls=true"
      - "traefik.http.routers.transmission-vpn-secure.tls.certresolver=le-dns"
      - "traefik.http.routers.transmission-vpn-secure.service=transmission-vpn"
      - "traefik.http.services.transmission-vpn.loadbalancer.server.port=9091"
    restart: unless-stopped

  transmission:
    container_name: transmission
    image: linuxserver/transmission:latest
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - TRANSMISSION_WEB_HOME=/combustion-release/
      - USER=${TRANSMISSION_USER}
      - PASS=${TRANSMISSION_PASS}
    volumes:
      - transmission-config:/config
      - transmission-downloads:/downloads
      - transmission-watchdir:/watch
      - /etc/localtime:/etc/localtime:ro
    # If NOT using the above VPN service uncomment the section below:
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.transmission.entrypoints=http"
    #   - "traefik.http.routers.transmission.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
    #   - "traefik.http.routers.transmission.middlewares=secured@file"
    #   - "traefik.http.routers.transmission-secure.entrypoints=https"
    #   - "traefik.http.routers.transmission-secure.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
    #   - "traefik.http.routers.transmission-secure.tls=true"
    #   - "traefik.http.routers.transmission-secure.tls.certresolver=le-dns"
    #   - "traefik.http.routers.transmission-secure.service=transmission"
    #   - "traefik.http.services.transmission.loadbalancer.server.port=9091"
    # networks:
    #   - proxy
    # ports:
    #   - 51413:51413
    #   - 51413:51413/udp
    network_mode: service:transmission-vpn
    depends_on:
      - transmission-vpn
    restart: unless-stopped